_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 2

accelerator: gpu
devices: [0]

# mixed precision for extra speed-up
precision: 16-mixed
profiler: null

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: 'warn' # AvgPool3d is non deterministic -> warn only

# gradient_batching: {0: 8, 4: 4, 8: 1}
accumulate_grad_batches: 1