# hpo search space, type defines the suggest_<type> function to use
model:
  optimizer:
    lr:
      type: "float"
      low: 1e-4
      high: 1e-1
      log: true
# data:
#   batch_size:
#     type: "categorical"
#     choices: [16, 32, 64, 128]  
  # bands:
  #   modis:
  #     type: "categorical"
  #     choices: [['sur_refl_b01','sur_refl_b02','sur_refl_b03','sur_refl_b04'], ['sur_refl_b01','sur_refl_b02','sur_refl_b03','sur_refl_b04','sur_refl_b06']]
# cnn-lstm
  net:
    spatial:
      # n_input_channels:
      #   type: "dependend"
      #   name: data.bands.modis
      #   choices: [10,11]
      num_classes:
        type: "int"
        low: 10
        high: 50
        step: 5
    temporal:
      hidden_dims: 
        type: "int"
        low: 32
        high: 256
        step: 32
      num_layers:
        type: "int"
        low: 1
        high: 3
      dropout:
        type: "float"
        low: 0.1
        high: 0.6
      # input_dim:
      #   type: "same"
      #   name: model.net.spatial.num_classes