loss:
  _target_: torchmetrics.MeanSquaredError
loss_agg:
  train:
    _target_: torchmetrics.MeanMetric
  val:
    _target_: torchmetrics.MeanMetric
  test:
    _target_: torchmetrics.MeanMetric
metrics:
  train:
    mae:
      _target_: torchmetrics.MeanAbsoluteError
    mse:
      _target_: torchmetrics.MeanSquaredError
      squared: True
    rmse:
      _target_: torchmetrics.MeanSquaredError
      squared: False
    r2:
      _target_: torchmetrics.R2Score
  val:
    mae:
      _target_: torchmetrics.MeanAbsoluteError
    mse:
      _target_: torchmetrics.MeanSquaredError
      squared: True
    rmse:
      _target_: torchmetrics.MeanSquaredError
      squared: False
    r2:
      _target_: torchmetrics.R2Score
  test:
    mae:
      _target_: torchmetrics.MeanAbsoluteError
    mse:
      _target_: torchmetrics.MeanSquaredError
      squared: True
    rmse:
      _target_: torchmetrics.MeanSquaredError
      squared: False
    r2:
      _target_: torchmetrics.R2Score
best_metric_agg:
  metric_name: mse # needs to be the metric name from the val metrics section
  monitor_mode: min
  metric:
    _target_: torchmetrics.MinMetric

# compile model for faster training with pytorch 2.0
compile: false
