cmlogger:
  _target_: src.utils.callbacks.PredLogger
  log_dir: "${paths.output_dir}/media/"
  name: "cm"
  every_n_epochs: 5
  plot_func:
    _target_: src.utils.visualizations.plot_confusion_matrix
    # handle_preds: 'round'
    _partial_: true
  # kwargs for torchmetrics.ConfusionMatrix
  task: ${model.metric_task_name}
  num_classes: ${model.num_classes}
  normalize: 'true'