cmlogger:
  _target_: src.utils.callbacks.PredLogger
  log_dir: "${paths.output_dir}/media/"
  name: "county_res"
  every_n_epochs: 1
  provide_meta_data: True
  plot_func:
    _target_: src.utils.visualizations.plot_county_residuals
    fn_counties: "${paths.data_dir}county_list.geojson"
    _partial_: true
