defaults:
  - _self_
  - train
  # - search_space/<filename>

study: # input to the create_study function
  _target_: optuna.create_study
  load_if_exists: True
  direction: minimize
  # direction: maximize
  study_name: fake-study
  storage: sqlite:///logs/optuna.db?timeout=60
  sampler:
    _target_: optuna.samplers.TPESampler
    n_startup_trials: 10
  pruner:
    # _target_: optuna.pruners.HyperbandPruner
    # min_resource: 10
    # max_resource: 'auto'
    # reduction_factor: 3
    _target_: optuna.pruners.MedianPruner
    n_startup_trials: 10
    n_warmup_steps: 20

optimize: # input to the optimize function
  n_trials: 50
  # timeout: 
  gc_after_trial: True
  # show_progress_bar: True
  # n_jobs: # does not work with wandb -> start different runs manually with storage
  callbacks:
    - _target_: optuna.study.MaxTrialsCallback
      n_trials: ${optimize.n_trials}
      states: [optuna.trial.TrialState.COMPLETE]
